### ISSUE TITLE
xbar v2.0.3-beta: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by matryer** [matryer/xbar#610]
**Are you experiencing this?** Please let us know your current operating system.

```
 ~ cd /Applications/xbar.app/Contents/MacOS
➜  MacOS ./xbar
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x44 pc=0x7fff201ff40d]

runtime stack:
runtime.throw(0x44db22d, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x2ef

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x43e6680, 0xc00018bda0, 0x0)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00018bd70 sp=0xc00018bd38 pc=0x4008cfb
github.com/wailsapp/wails/v2/internal/ffenestri._Cfunc_Run(0xb904110, 0xc000000000, 0x0)
```

<details>
 ~ cd /Applications/xbar.app/Contents/MacOS
➜  MacOS ./xbar
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x44 pc=0x7fff201ff40d]

runtime stack:
runtime.throw(0x44db22d, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x2ef

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x43e6680, 0xc00018bda0, 0x0)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00018bd70 sp=0xc00018bd38 pc=0x4008cfb
github.com/wailsapp/wails/v2/internal/ffenestri._Cfunc_Run(0xb904110, 0xc000000000, 0x0)
	_cgo_gotypes.go:359 +0x45 fp=0xc00018bda0 sp=0xc00018bd70 pc=0x43cbf45
github.com/wailsapp/wails/v2/internal/ffenestri.(*Application).Run.func6(0xb904110)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/ffenestri/ffenestri.go:171 +0x65 fp=0xc00018bdd0 sp=0xc00018bda0 pc=0x43cece5
github.com/wailsapp/wails/v2/internal/ffenestri.(*Application).Run(0xc000158380, 0x4568be0, 0xc000138dc0, 0xc0001f8a80, 0x95a, 0xc000158a00, 0x0, 0x0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/ffenestri/ffenestri.go:171 +0x2f1 fp=0xc00018be40 sp=0xc00018bdd0 pc=0x43cd431
github.com/wailsapp/wails/v2/internal/app.(*App).Run(0xc00015d290, 0xc00015d290, 0x0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/app/desktop.go:224 +0x659 fp=0xc00018bee8 sp=0xc00018be40 pc=0x43db219
github.com/wailsapp/wails/v2.Run(0xc0001cc000, 0xc000158200, 0x44c7ab3)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/wails.go:24 +0x5f fp=0xc00018bf18 sp=0xc00018bee8 pc=0x43db83f
main.main()
	/Users/matryer/Code/go/src/github.com/matryer/xbar/app/main.go:17 +0x30e fp=0xc00018bf88 sp=0xc00018bf18 pc=0x43e0b8e
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc00018bfe0 sp=0xc00018bf88 pc=0x403dbb6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00018bfe8 sp=0xc00018bfe0 pc=0x40712a1

goroutine 19 [select]:
github.com/wailsapp/wails/v2/internal/servicebus.(*ServiceBus).Start.func1(0xc0001343c0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/servicebus/servicebus.go:83 +0x157
created by github.com/wailsapp/wails/v2/internal/servicebus.(*ServiceBus).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/servicebus/servicebus.go:77 +0xce

goroutine 20 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Runtime).Start.func1(0xc000134f60)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/runtime.go:73 +0x17c
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Runtime).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/runtime.go:70 +0x3f

goroutine 21 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Log).Start.func1(0xc000136320)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/log.go:68 +0x157
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Log).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/log.go:64 +0x5c

goroutine 22 [select]:
github.com/wailsapp/wails/v2/internal/messagedispatcher.(*Dispatcher).Start.func1(0xc000138dc0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/messagedispatcher/messagedispatcher.go:118 +0x225
created by github.com/wailsapp/wails/v2/internal/messagedispatcher.(*Dispatcher).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/messagedispatcher/messagedispatcher.go:115 +0x9e

goroutine 23 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*URL).Start.func1(0xc0001365f0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/url.go:66 +0x157
created by github.com/wailsapp/wails/v2/internal/subsystem.(*URL).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/url.go:62 +0x5c

goroutine 24 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Event).Start.func1(0xc000136690)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/event.go:89 +0x153
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Event).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/event.go:86 +0x9b

goroutine 25 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Menu).Start.func1(0xc000136730)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/menu.go:72 +0x153
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Menu).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/menu.go:69 +0x9b

goroutine 26 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Call).Start.func1(0xc0001367d0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/call.go:77 +0x14a
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Call).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/call.go:74 +0x5a

goroutine 34 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x45

goroutine 28 [select]:
github.com/wailsapp/wails/v2/internal/signal.(*Manager).Start.func1(0xc000158a00)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/signal/signal.go:59 +0x9e
created by github.com/wailsapp/wails/v2/internal/signal.(*Manager).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/signal/signal.go:58 +0xc9
</details>

**Comment by AlekSi** [comment]
The same problem with v2.0.5-beta – but I'm sure you are aware of it :)

**Comment by matryer** [comment]
@AlekSi Thanks. What macOS are you running?

**Comment by AlekSi** [comment]
macOS 11.2.2 (20D80) – the latest Big Sur

**Comment by matryer** [comment]
@AlekSi How do you run xbar.app? Right click and Open?

**Comment by AlekSi** [comment]
When I run it with the right click and open, it exits immediately. I tried that a couple of times, then decided to look into it and run just like you show in the gist.

**Comment by matryer** [comment]
@AlekSi ah you're ahead of me :) We're actively trying to figure out what's going on here. cc @leaanthony

**Comment by leaanthony** [comment]
@AlekSi Is there anything showing up in Apple's `console` app related to this? Struggling to reproduce here.

**Comment by om4csaba** [comment]
Sam error with v2.0.10-beta on macOS 11.2.2 (20D80)

Console output:
```
Mar  9 08:55:08 om4mbp xbar[68187]: getattrlist failed for /System/Library/Extensions/AppleIntelKBLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsGLDriver: #2: No such file or directory
Mar  9 08:55:08 om4mbp xbar[68187]: getattrlist failed for /Library/GPUBundles/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/ATIRadeonX4000SCLib.dylib: #2: No such file or directory
Mar  9 08:55:08 om4mbp xbar[68187]: getattrlist failed for /System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/ATIRadeonX4000SCLib.dylib: #2: No such file or directory
Mar  9 08:55:08 om4mbp xbar[68187]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
```

Command line:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x44 pc=0x7fff2044540d]

runtime stack:
runtime.throw(0x44dbc52, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x2ef

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x43e7060, 0xc0000f1da0, 0x0)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0000f1d70 sp=0xc0000f1d38 pc=0x4008e7b
github.com/wailsapp/wails/v2/internal/ffenestri._Cfunc_Run(0x4e04260, 0xc000000000, 0x0)
	_cgo_gotypes.go:359 +0x45 fp=0xc0000f1da0 sp=0xc0000f1d70 pc=0x43cc925
github.com/wailsapp/wails/v2/internal/ffenestri.(*Application).Run.func6(0x4e04260)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/ffenestri/ffenestri.go:171 +0x65 fp=0xc0000f1dd0 sp=0xc0000f1da0 pc=0x43cf6c5
github.com/wailsapp/wails/v2/internal/ffenestri.(*Application).Run(0xc0000823c0, 0x45696a0, 0xc0000a4e60, 0xc0001d8a80, 0x95a, 0xc000082a00, 0x0, 0x0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/ffenestri/ffenestri.go:171 +0x2f1 fp=0xc0000f1e40 sp=0xc0000f1dd0 pc=0x43cde11
github.com/wailsapp/wails/v2/internal/app.(*App).Run(0xc0000c3290, 0xc0000c3290, 0x0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/app/desktop.go:224 +0x659 fp=0xc0000f1ee8 sp=0xc0000f1e40 pc=0x43dbbf9
github.com/wailsapp/wails/v2.Run(0xc0001b2000, 0xc000082240, 0x44c8493)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/wails.go:24 +0x5f fp=0xc0000f1f18 sp=0xc0000f1ee8 pc=0x43dc21f
main.main()
	/Users/matryer/Code/go/src/github.com/matryer/xbar/app/main.go:17 +0x30e fp=0xc0000f1f88 sp=0xc0000f1f18 pc=0x43e158e
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc0000f1fe0 sp=0xc0000f1f88 pc=0x403dd36
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000f1fe8 sp=0xc0000f1fe0 pc=0x4071681

goroutine 6 [select]:
github.com/wailsapp/wails/v2/internal/servicebus.(*ServiceBus).Start.func1(0xc000034480)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/servicebus/servicebus.go:83 +0x157
created by github.com/wailsapp/wails/v2/internal/servicebus.(*ServiceBus).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/servicebus/servicebus.go:77 +0xce

goroutine 7 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Runtime).Start.func1(0xc000035020)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/runtime.go:73 +0x17c
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Runtime).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/runtime.go:70 +0x3f

goroutine 8 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Log).Start.func1(0xc00008c370)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/log.go:68 +0x157
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Log).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/log.go:64 +0x5c

goroutine 9 [select]:
github.com/wailsapp/wails/v2/internal/messagedispatcher.(*Dispatcher).Start.func1(0xc0000a4e60)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/messagedispatcher/messagedispatcher.go:118 +0x225
created by github.com/wailsapp/wails/v2/internal/messagedispatcher.(*Dispatcher).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/messagedispatcher/messagedispatcher.go:115 +0x9e

goroutine 10 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*URL).Start.func1(0xc00008c640)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/url.go:66 +0x157
created by github.com/wailsapp/wails/v2/internal/subsystem.(*URL).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/url.go:62 +0x5c

goroutine 11 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Event).Start.func1(0xc00008c6e0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/event.go:89 +0x153
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Event).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/event.go:86 +0x9b

goroutine 12 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Menu).Start.func1(0xc00008c780)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/menu.go:72 +0x153
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Menu).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/menu.go:69 +0x9b

goroutine 13 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Call).Start.func1(0xc00008c820)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/call.go:77 +0x14a
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Call).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/call.go:74 +0x5a

goroutine 15 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x45

goroutine 18 [select]:
github.com/wailsapp/wails/v2/internal/signal.(*Manager).Start.func1(0xc000082a40)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/signal/signal.go:59 +0x9e
created by github.com/wailsapp/wails/v2/internal/signal.(*Manager).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/signal/signal.go:58 +0xc9
```

**Comment by leaanthony** [comment]
Thanks @AlekSi - googling the missing dylibs it seems like it's a common issue with a bunch of apps. This report specifically mentions this for the same machine (MacBook Pro 15" 2018): https://discussions.apple.com/thread/252183335
Are you seeing the same errors for other apps?

**Comment by AlekSi** [comment]
That wasn't me :)

**Comment by om4csaba** [comment]
@leaanthony I can see a couple of it, but not too much. 

Occasionally by Webkit and ScreenSaverEngine. [Insomnia's](https://insomnia.rest) Helper process also log it, but not causing any visible problem.

**Comment by leaanthony** [comment]
Are you comfortable running lldb to get a backtrace?

**Comment by om4csaba** [comment]
Here is mine lldb output:

<details>
 <summary>Details</summary>

```
lldb -- ./xbar
(lldb) target create "./xbar"
Current executable set to '/Applications/xbar.app/Contents/MacOS/xbar' (x86_64).
(lldb) run
Process 68896 launched: '/Applications/xbar.app/Contents/MacOS/xbar' (x86_64)
2021-03-09 19:16:29.711574+0800 xbar[68896:1850166] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=68896
2021-03-09 19:16:29.711660+0800 xbar[68896:1850166] SecTaskCopyDebugDescription: xbar[68896]/0#-1 LF=0
2021-03-09 19:16:29.988645+0800 xbar[68896:1850209] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=68896
2021-03-09 19:16:29.988730+0800 xbar[68896:1850209] SecTaskCopyDebugDescription: xbar[68896]/0#-1 LF=0
2021-03-09 19:16:31.980050+0800 xbar[68896:1850166] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=68896
2021-03-09 19:16:31.980164+0800 xbar[68896:1850166] SecTaskCopyDebugDescription: xbar[68896]/0#-1 LF=0
Process 68896 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x44)
    frame #0: 0x00007fff2044540d libobjc.A.dylib`class_conformsToProtocol + 309
libobjc.A.dylib`class_conformsToProtocol:
->  0x7fff2044540d <+309>: testl  %eax, 0x44(%rbx)
    0x7fff20445410 <+312>: jne    0x7fff20445427            ; <+335>
    0x7fff20445412 <+314>: movq   0x8(%rbx), %rdi
    0x7fff20445416 <+318>: callq  0x7fff2043e0dc            ; getProtocol(char const*)
Target 0: (xbar) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x44)
  * frame #0: 0x00007fff2044540d libobjc.A.dylib`class_conformsToProtocol + 309
    frame #1: 0x00007fff204452b6 libobjc.A.dylib`-[NSObject conformsToProtocol:] + 47
    frame #2: 0x00007fff2355e802 AppKit`-[NSApplication(NSTouchBarFinder) NS_touchBarProviders] + 401
    frame #3: 0x00007fff2355f99a AppKit`_NSTouchBarFinderGatherProvidersForContainer + 64
    frame #4: 0x00007fff2355facc AppKit`_NSTouchBarFinderGatherProvidersForContainer + 370
    frame #5: 0x00007fff2355facc AppKit`_NSTouchBarFinderGatherProvidersForContainer + 370
    frame #6: 0x00007fff2355f034 AppKit`___NSTouchBarFinderSetNeedsUpdateOnMain_block_invoke_2 + 535
    frame #7: 0x00007fff22f8e8f8 AppKit`NSDisplayCycleObserverInvoke + 155
    frame #8: 0x00007fff22f8e482 AppKit`NSDisplayCycleFlush + 937
    frame #9: 0x00007fff26e38f5e QuartzCore`CA::Transaction::run_commit_handlers(CATransactionPhase) + 92
    frame #10: 0x00007fff26e37d04 QuartzCore`CA::Transaction::commit() + 382
    frame #11: 0x00007fff2303de22 AppKit`__62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 285
    frame #12: 0x00007fff2378cec2 AppKit`___NSRunLoopObserverCreateWithHandler_block_invoke + 41
    frame #13: 0x00007fff2069adad CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    frame #14: 0x00007fff2069ac3d CoreFoundation`__CFRunLoopDoObservers + 549
    frame #15: 0x00007fff2069a0ed CoreFoundation`__CFRunLoopRun + 838
    frame #16: 0x00007fff206996ce CoreFoundation`CFRunLoopRunSpecific + 563
    frame #17: 0x00007fff28921630 HIToolbox`RunCurrentEventLoopInMode + 292
    frame #18: 0x00007fff28921282 HIToolbox`ReceiveNextEventCommon + 283
    frame #19: 0x00007fff2892114f HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 64
    frame #20: 0x00007fff22eb99b1 AppKit`_DPSNextEvent + 883
    frame #21: 0x00007fff22eb8177 AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1366
    frame #22: 0x00007fff22eaa68a AppKit`-[NSApplication run] + 586
    frame #23: 0x00000000043f396c xbar`Run + 4076
    frame #24: 0x00000000043e708f xbar`_cgo_0185d2c5ec34_Cfunc_Run + 47
    frame #25: 0x0000000004071310 xbar`runtime.asmcgocall + 112
    frame #26: 0x00000000043cc925 xbar`github.com/wailsapp/wails/v2/internal/ffenestri._Cfunc_Run + 69
    frame #27: 0x00000000043cf6c5 xbar`github.com/wailsapp/wails/v2/internal/ffenestri.(*Application).Run.func6 + 101
    frame #28: 0x00000000043cde11 xbar`github.com/wailsapp/wails/v2/internal/ffenestri.(*Application).Run + 753
    frame #29: 0x00000000043dbbf9 xbar`github.com/wailsapp/wails/v2/internal/app.(*App).Run + 1625
    frame #30: 0x00000000043dc21f xbar`github.com/wailsapp/wails/v2.Run + 95
    frame #31: 0x00000000043e158e xbar`main.main + 782
    frame #32: 0x000000000403dd36 xbar`runtime.main + 598
    frame #33: 0x0000000004071681 xbar`runtime.goexit + 1
    frame #34: 0x00000000043cf6c5 xbar`github.com/wailsapp/wails/v2/internal/ffenestri.(*Application).Run.func6 + 101
    frame #35: 0x00000000043cde11 xbar`github.com/wailsapp/wails/v2/internal/ffenestri.(*Application).Run + 753
    frame #36: 0x00000000043dbbf9 xbar`github.com/wailsapp/wails/v2/internal/app.(*App).Run + 1625
    frame #37: 0x00000000043dc21f xbar`github.com/wailsapp/wails/v2.Run + 95
    frame #38: 0x00000000043e158e xbar`main.main + 782
    frame #39: 0x000000000403dd36 xbar`runtime.main + 598
    frame #40: 0x0000000004071681 xbar`runtime.goexit + 1
    frame #41: 0x00000000043cde11 xbar`github.com/wailsapp/wails/v2/internal/ffenestri.(*Application).Run + 753
    frame #42: 0x00000000043dbbf9 xbar`github.com/wailsapp/wails/v2/internal/app.(*App).Run + 1625
    frame #43: 0x00000000043dc21f xbar`github.com/wailsapp/wails/v2.Run + 95
    frame #44: 0x00000000043e158e xbar`main.main + 782
    frame #45: 0x000000000403dd36 xbar`runtime.main + 598
    frame #46: 0x0000000004071681 xbar`runtime.goexit + 1
    frame #47: 0x00000000043dbbf9 xbar`github.com/wailsapp/wails/v2/internal/app.(*App).Run + 1625
    frame #48: 0x00000000043dc21f xbar`github.com/wailsapp/wails/v2.Run + 95
    frame #49: 0x00000000043e158e xbar`main.main + 782
    frame #50: 0x000000000403dd36 xbar`runtime.main + 598
    frame #51: 0x0000000004071681 xbar`runtime.goexit + 1
    frame #52: 0x00000000043dc21f xbar`github.com/wailsapp/wails/v2.Run + 95
    frame #53: 0x00000000043e158e xbar`main.main + 782
    frame #54: 0x000000000403dd36 xbar`runtime.main + 598
    frame #55: 0x0000000004071681 xbar`runtime.goexit + 1
    frame #56: 0x00000000043e158e xbar`main.main + 782
    frame #57: 0x000000000403dd36 xbar`runtime.main + 598
    frame #58: 0x0000000004071681 xbar`runtime.goexit + 1
    frame #59: 0x000000000403dd36 xbar`runtime.main + 598
    frame #60: 0x0000000004071681 xbar`runtime.goexit + 1
    frame #61: 0x0000000004071681 xbar`runtime.goexit + 1
(lldb)
```
</details>

**Comment by matryer** [comment]
cc @AlekSi @om4csaba 

Please try [the latest release](https://github.com/matryer/xbar/releases) - we've addressed the TouchBar issue.

**Comment by AlekSi** [comment]
Yep, it starts now! 🥳

**Comment by matryer** [comment]
@AlekSi great - let me know if you have any other problems.

**Comment by matryer** [comment]
Closing as I think this is resolved. We'll open if we see other similar panics on different machines.
